# Generated by Django 2.2.7 on 2019-12-20 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumapp', '0003_auto_20191220_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id_user',
            field=models.ManyToManyField(related_name='user_board', to=settings.AUTH_USER_MODEL, verbose_name='utente'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrumapp.Column', verbose_name='colonna'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id_user_card',
            field=models.ManyToManyField(related_name='user_card', to=settings.AUTH_USER_MODEL, verbose_name='utente'),
        ),
        migrations.AlterField(
            model_name='column',
            name='id_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrumapp.Board', verbose_name='board'),
        ),
    ]
