# Generated by Django 2.2.7 on 2019-12-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=100, verbose_name='titolo'),
        ),
    ]
