# Generated by Django 2.2.7 on 2019-11-17 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumapp', '0002_auto_20191117_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='user',
            field=models.ManyToManyField(related_name='user_board', to=settings.AUTH_USER_MODEL),
        ),
    ]
