# Generated by Django 2.2.7 on 2019-11-17 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrumapp', '0003_auto_20191117_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
        migrations.AddField(
            model_name='board',
            name='user_of_board',
            field=models.ManyToManyField(related_name='user_board', to=settings.AUTH_USER_MODEL),
        ),
    ]
