# Generated by Django 2.2.7 on 2019-11-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumapp', '0004_auto_20191117_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user_of_board',
            new_name='user',
        ),
    ]
