# Generated by Django 2.2.7 on 2019-11-18 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrumapp', '0006_auto_20191118_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ManyToManyField(related_name='user_board', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UtenteBoard',
        ),
    ]
