# Generated by Django 2.2.7 on 2019-11-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumapp', '0007_auto_20191118_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user',
            new_name='id_user',
        ),
    ]
