# Generated by Django 2.2.7 on 2019-11-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumapp', '0008_auto_20191118_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrumapp.Board')),
            ],
        ),
    ]
