# Generated by Django 2.2.7 on 2019-11-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumapp', '0009_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('id_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrumapp.Column')),
            ],
        ),
    ]
