# Generated by Django 2.2.7 on 2019-11-22 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumapp', '0010_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(default=[('', '---------')]),
        ),
        migrations.AddField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
