# Generated by Django 2.2.7 on 2019-11-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumapp', '0012_auto_20191122_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='story_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
