# Generated by Django 2.2.7 on 2019-11-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumapp', '0013_card_story_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='story_points',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=range(1, 5)),
        ),
    ]
